src/ViewComponents/RazorPageNavItemsViewComponent.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Razor.Language;
using Microsoft.Extensions.Options;
using socialarts.club.ObjectExtensions;
using socialarts.club.IEnumerableExtensions;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using socialarts.club.ViewComponents.Extensions;

namespace socialarts.club.ViewComponents
{
    // TODO Reconsider coupling the nabar to the file system.
    public class RazorPageNavItemsViewComponent : ViewComponent
    {
        private readonly IActionDescriptorCollectionProvider _provider;

        public RazorPageNavItemsViewComponent(IActionDescriptorCollectionProvider provider)
        {
            _provider = provider;
        }

        public IViewComponentResult Invoke(string viewName)
        {
            var allActions = _provider.ActionDescriptors.Items;

            var pageActions = allActions
                .Where(a => a is PageActionDescriptor)
                .Cast<PageActionDescriptor>();

            var areaGroups = pageActions.GroupBy(a => a.AreaName);

            var defaultAreaActions = areaGroups
                .Where(g => g.Key == null)
                .SelectMany(g => g);

            var nestingGroups = defaultAreaActions
                .GroupBy(a => a.ViewEnginePath.Split("/").Skip(1).Count());

            var rootItems = nestingGroups
                .Where(g => g.Key == 1)
                .SelectMany(g => g)
                .Select(a => new NavItemViewModel
                {
                    Title = a.ViewEnginePath.TrimStart('/'),
                    Path = a.ViewEnginePath,
                });

            var childItems = nestingGroups
                .Where(g => g.Key == 2)
                .SelectMany(g => g)
                .GroupBy(a => a.ViewEnginePath.Split("/").Skip(1).First())
                .ToDictionary(
                    g => g.Key, 
                    g => g.Select(a => new NavItemViewModel 
                    { 
                        Title = a.ViewEnginePath.Split("/").Last(),
                        Path = a.ViewEnginePath
                    })
                );

            var model = new RazorPageNavItemsViewComponentModel
            {
                ItemsWithoutChildren = rootItems,
                ItemsThatHaveChildren = childItems
            };

            return View(viewName, model);
        }
    }
}

src/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - socialarts.club</title>
    <link href="~/site.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <partial name="_CookieConsentPartial" />
    <partial name="_Navbar" />
    <div class="container body-content">
        <main class="row">
            <div class="col-12">
                <header class="sa-page-header">
                    <h1>@ViewData["Title"]</h1>
                </header>
            </div>
            <div class="col-12">
                @RenderBody()
            </div>
        </main>
        <footer>
            Open source on the <a href="https://github.com/shaunluttin/socialarts.club">GitHub</a>.
        </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- Load React. -->
    <!-- Note: when deploying, replace "development.js" with "production.min.js". -->
    <script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin></script>
    <script src="~/react-components/bundle.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/Pages/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">socialarts.club</a>
  <button 
    class="navbar-toggler" 
    type="button" 
    data-toggle="collapse" 
    data-target="#navbarNavDropdown" 
    aria-controls="navbarNavDropdown" 
    aria-expanded="false" 
    aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <vc:razor-page-nav-items view-name="MainNavItems"></vc:razor-page-nav-items>
        </ul>
        <div class="ml-auto">
          <partial name="_LoginPartial" />
        </div>
  </div>
</nav>

src/Pages/Shared/_SiteLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - socialarts.club</title>
    <script src="~/dist/early.bundle.js" asp-append-version="true"></script>
</head>
<body>
    <partial name="_CookieConsentPartial" />
    <partial name="_Navbar" />
    <div class="container body-content">
        <main class="row">
            <div class="col-12">
                <header class="sa-page-header">
                    <h1>@ViewData["Title"]</h1>
                </header>
            </div>
            <div class="col-12">
                @RenderBody()
            </div>
        </main>
        <footer>
            Open source on the <a href="https://github.com/shaunluttin/socialarts.club">GitHub</a>.
        </footer>
    </div>
    <script src="~/dist/late.bundle.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>